#!/bin/bash

# Start Docker (ignore error if already running)
sudo systemctl start docker || true

# Check if container exists and remove it
if [ "$(sudo docker ps -aq -f name=my-app)" ]; then
    sudo docker stop my-app
    sudo docker rm my-app
fi

# Run new container
sudo docker run -d -p 80:8000 \
  -e DAGSHUB_PAT=CODE_HERE \
  --name my-app \
  851725541946.dkr.ecr.ap-south-1.amazonaws.com/autonexus_ecr_image:latest
